enum QueryOperator {
  EQUAL,
  NOT_EQUAL,
  GREATER_THAN,
  GREATER_THAN_OR_EQUAL,
  LESS_THAN,
  LESS_THAN_OR_EQUAL,
  CONTAINS,
  DOES_NOT_CONTAIN,
  IN,
  NOT_IN,
  IS_NULL,
  IS_NOT_NULL,
}

export default QueryOperator;